name: Cleanup Merged Branches

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'main' && github.event.pull_request.head.ref != 'develop'

    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `heads/${branchName}`
              });

              console.log(`✅ Successfully deleted branch: ${branchName}`);

              // Comment on the PR about branch deletion
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: context.issue.number,
                body: `🗑️ **Branch cleanup completed**

                The feature branch \`${branchName}\` has been automatically deleted after merge.`
              });

            } catch (error) {
              console.log(`❌ Failed to delete branch ${branchName}: ${error.message}`);

              // Only fail if it's not a "branch not found" error
              if (!error.message.includes('Git Repository is empty') && !error.message.includes('Not Found')) {
                core.setFailed(`Failed to delete branch: ${error.message}`);
              }
            }
